# Site settings
title: Code for Hawaii
email: info@codeforhawaii.org
url: http://codeforhawaii.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Code for Hawaii

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/codeforhawaii
  - title: github
    url: https://github.com/codeforhawaii

# Build settings
markdown: kramdown
permalink: pretty
