# Site settings
title: Code for Hawaii | Code for America Brigade
email: info@codeforhawaii.org
url: http://codeforhawaii.org
description: "Code for Hawaii is a Code for America Brigade.  We are volunteers interested in open data, open knowledge, civic apps, big data, data visualization, APIs and the application of technology to make our communities better.  We encourage civic engagement and collaboration with our local government."
keywords: "code for hawaii, code, hawaii, civic apps, open data, data visualization, apis, application of technology, technology, code for america"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Code for Hawaii

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/codeforhawaii
  - title: github
    url: https://github.com/codeforhawaii
  - title: facebook
    url: https://facebook.com/codeforhawaii

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap

exclude:
  - vendor
  - README.md
  - LICENSE.md
  - Vagrantfile
  - Gemfile
  - .travis.yml
